matrix:
  allow_failures:
  language: bash
  sudo: false
  include:

    - os: linux
      dist: bionic
      script:
      env: PATH=/usr/bin:/bin:./:/usr/local/bin
        - openssl version
        - shellcheck --version
        - bash -c 'export SHELLCHECK_OPTS="-S warning -e SC2006"; shopt -s globstar; shellcheck **/*.sh easyrsa3/easyrsa'
        - sh op_test.sh -vv

    - os: osx
      osx_image: xcode10.1
      script:
        - sh op_test.sh -vv
