language: bash

sudo: false

addons:
  apt:
    sources:
    - debian-sid
    packages:
    - shellcheck

script:
 - bash -c 'export SHELLCHECK_OPTS="-e SC2006"; shopt -s globstar; shellcheck **/*.sh easyrsa3/easyrsa'
 - bash -c 'pwd'
 - bash -c 'ls -la'
 - bash -c 'sh -x op_test.sh'
